fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    vcsrepo: "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    python: "git://github.com/stankevich/puppet-python.git"
    apache: 'git://github.com/puppetlabs/puppetlabs-apache.git'
  symlinks:
    puppetboard: "#{source_dir}"
